---
- name: Main playbook
  hosts: all
  become: true
  tasks:
  - name: Import the role
    include_role: 
      name: install_apache
  - name: Import another role
    include_role:
      name: security
